### ISSUE TITLE
Highlighting in the GUI

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#12] opened 2018-08-22 22:07 UTC
Highlighting of phrases is broken in the GUI.

- The menu items are all bold, but only the words that replace the selected words should be bold. The rest should be greyed out.

- Matching phrases between the top and bottom sentence are not highlighted.

**Comment by heatherleaf** [comment] 2018-08-23 11:44
Sorry, not working in full yet. Here's a sequence from the first "Prima Pars" exercise:

First click on "fadern" to get the menu:
![image](https://user-images.githubusercontent.com/1324196/44523504-61e0bd80-a6da-11e8-8359-03ecf2ea988b.png)

Then select "Augustus är lycklig":
![image](https://user-images.githubusercontent.com/1324196/44523511-66a57180-a6da-11e8-8e45-a02edeb06d90.png)

All highlighting in the Swedish sentence go away. 

Also, the system doesn't report that the exercise is finished. (Should I create a separate bug for that?)

**Comment by fredefox** [comment] 2018-08-24 09:35
The lack of highlighting when the exercise is over is a separate issue and related with the regression that finished exercises are not correctly detected. I've created a new issue for this at #16

**Comment by fredefox** [comment] 2018-08-24 09:36
Actually I think I'll close this in favor of #16. We can reopen this if problems related to highlighting persist after this.

**Comment by heatherleaf** [comment] 2018-08-24 10:40
No, the highlighting is another problem than not detecting a finished exercise. See here:

![image](https://user-images.githubusercontent.com/1324196/44580528-95831c80-a79a-11e8-8102-1b6ee63b85e2.png)

Replace "lycklig" with "orolig" (now "är" should still be highlighted): 

![image](https://user-images.githubusercontent.com/1324196/44580534-99af3a00-a79a-11e8-9576-cbe6eaed3777.png)

Replace "orolig" with "lycklig" (now this should look like the starting image):

![image](https://user-images.githubusercontent.com/1324196/44580542-9caa2a80-a79a-11e8-8a4c-ea2e69c8dd4d.png)

**Comment by heatherleaf** [comment] 2018-08-24 10:41
But, wait with this until later -- there are other concerns with paths that we have to solve first. (issue #15)

**Comment by fredefox** [comment] 2018-08-24 12:05
So the problem is related to:

https://github.com/MUSTE-Project/MULLE/blob/0c6bf57f60c2e5e4671fa7094b567a6872e67f36/muste-ajax/src/Protocol.hs#L354-L368

As you can see we're not using the source- and target tree here (3rd and 4th arg). The reason it's in the signature is because we used to, when server trees consisted of TTrees. We used these to create the matching information. So we need to figure out how to do this now. The ClientTrees we receive do not have information about matching.

**Comment by heatherleaf** [comment] 2018-08-26 23:32
Some new ideas for highlighting is in #19

**Comment by heatherleaf** [comment] 2018-09-03 13:42
Seems fine now, or do you know of any remaining problem regarding highlighting?

**Comment by fredefox** [comment] 2018-09-04 06:40
The way I implemented highlighting was to calculate a hash value from the name of the internal node, and from this I generate an rgb-value. The hashing algorithm is very much held together with duct tape, but I don't think this is really a big issue. I'd say we can close this.

**Closed by fredefox** 2018-09-04 06:40 UTC
Labels: bug
